### ISSUE TITLE
fireplace switch should trigger status report

### ISSUE THREAD

**Issue by priiduonu** [kotope/valloxesp#4] opened 2021-05-21 23:05 UTC
it seems `statusChangedCallback();` should be called in the end of

```
void Vallox::setSwitchOn() {
          // Activate boost/fireplace
          setVariable(VX_VARIABLE_FLAGS_06, data.flags06.value | VX_06_FIREPLACE_FLAG_ACTIVATE);
        }
```
otherwise the switching off of the exhaust motor is reported only in up to 5 minutes later.

**Comment by kotope** [comment] 2021-05-22 07:07
Actually this might be something that works differently between models.

In my Vallox 121SE "flags 06" variable is pushed straight away by Vallox main board after variable is being set, so at least on my case it, is set as active immediately. 
However, I think this would not break anything even if set directly after setting the variable. 

I will make the change today, thanks for reporting the issue!

**Comment by kotope** [comment] 2021-05-22 07:12
Read your issue again that you wrote 'switching off' and actually you are absolutely right!

The switch setting off is not reported since the value is already known (wrongly).
Will fix it :-)

**Comment by priiduonu** [comment] 2021-05-22 08:11
Thanks!

Also - I have Vallox Digit SE and in my case the `switch_active` seems to stay `false` all the time, even after activating the fireplace mode. Maybe this model behaves different. Does your 121SE report `switch_active: true` when in fireplace mode?

**Comment by kotope** [comment] 2021-05-23 07:10
Hi,

switch_active is working correctly at least with my 121SE. 
Just verified with mqtt client (first line is the setter and directly after that 121SE is reporting it correctly)

vallox/set {"activate_switch": true}
vallox/state {"mode":"FAN","heating":false,"on":true,"fault":false,"rh_mode":false,"service_needed":false,"summer_mode":false,"motor_in":true,"motor_out":true,"front_heating":false,"speed":4,"default_fan_speed":1,"service_period":4,"service_counter":3,"heat_target":10,"switch_active":true,"valloxesp_sw_version":"0.8.1","switch_type":"fireplace"}

**Comment by kotope** [comment] 2021-05-23 07:26
Also just tested that fireplace switch deactivating after 15minutes (with vallox counter) seems to work ok even without the fix, so this original issue does not reproduce in my machine at least.

Will anyhow try with the 'fix' implemented and verify that it will not cause any regression.

**Comment by priiduonu** [comment] 2021-05-24 17:55
Captured some packets:

```
{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9f 06 "}
{"packetRecv":"01 11 20 34 a7 0d "}
{"packetRecv":"01 11 20 32 84 e8 "}
{"packetRecv":"01 11 20 33 91 f6 "}
{"packetRecv":"01 11 20 2a 29 85 "}

{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9f 06 "}
{"packetRecv":"01 11 20 34 a7 0d "}
{"packetRecv":"01 11 20 32 84 e8 "}
{"packetRecv":"01 11 20 33 91 f6 "}
{"packetRecv":"01 11 20 2a 29 85 "}

{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9f 06 "}
{"packetRecv":"01 11 20 34 a7 0d "}
{"packetRecv":"01 11 20 32 84 e8 "}
{"packetRecv":"01 11 20 33 92 f7 "}
{"packetRecv":"01 11 20 2a 29 85 "}

{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9f 06 "}
{"packetRecv":"01 11 20 34 a8 0e "}
{"packetRecv":"01 11 20 32 84 e8 "}
{"packetRecv":"01 11 20 33 92 f7 "}
{"packetRecv":"01 11 20 2a 29 85 "}

{"packetSent":"01 22 11 00 08 3c "}
{"packetSent":"01 22 11 00 ab df "}
{"packetRecv":"01 11 22 08 01 3d "}
{"packetRecv":"01 11 22 ab 01 e0 "}

{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9f 06 "}
{"packetRecv":"01 11 20 34 a8 0e "}
{"packetRecv":"01 11 20 32 84 e8 "}
{"packetRecv":"01 11 20 33 92 f7 "}
{"packetRecv":"01 11 20 2a 29 85 "}
```

**Comment by kotope** [comment] 2021-05-26 06:00
This log does not seem to include fireplace activate at all? Can you get logs when you send the 'switch activate' command to your Vallox so I can compare it with my machine?

**Comment by priiduonu** [comment] 2021-05-26 12:25
"normal mode" (7 packets in every 15 seconds):

```
{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9a 01 "}
{"packetRecv":"01 11 20 34 a6 0c "}
{"packetRecv":"01 11 20 32 81 e5 "}
{"packetRecv":"01 11 20 33 90 f5 "}
{"packetRecv":"01 11 20 2a 29 85 "}
```
after vallox/set {"activate_switch": true}

```
{"packetSent":"01 22 10 71 20 c4 "}

{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 9a 01 "}
{"packetRecv":"01 11 20 34 a6 0c "}
{"packetRecv":"01 11 20 32 81 e5 "}
{"packetRecv":"01 11 20 33 90 f5 "}
{"packetRecv":"01 11 20 2a 29 85 "}
```
(7 packets repeating in every 15 seconds):

```
{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 99 00 "}
{"packetRecv":"01 11 20 34 a6 0c "}
{"packetRecv":"01 11 20 32 81 e5 "}
{"packetRecv":"01 11 20 33 90 f5 "}
{"packetRecv":"01 11 20 2a 29 85 "}
```
after 15 minutes had passed, no special packets were detected, the first 7 packets captured:

```
{"packetRecv":"01 11 20 2b 00 5d "}
{"packetRecv":"01 11 20 2c 00 5e "}
{"packetRecv":"01 11 20 35 98 ff "}
{"packetRecv":"01 11 20 34 a3 09 "}
{"packetRecv":"01 11 20 32 81 e5 "}
{"packetRecv":"01 11 20 33 86 eb "}
{"packetRecv":"01 11 20 2a 29 85 "}
```
hope this helps

**Comment by kotope** [comment] 2021-05-26 13:28
Thanks for the logs.

It seems that your machine is not sending the 0x71H (flags 06) variable after switch state changes.
Here is the 'switch active' message from my machine:
vallox/debug {"packetSent":"01 22 10 71 20 c4 "}
vallox/debug {"packetRecv":"01 21 11 00 a3 d6 "}
vallox/debug {"packetRecv":"01 11 21 a3 01 d7 "}
vallox/debug {"packetRecv":"01 21 11 00 29 5c "}
vallox/debug {"packetRecv":"01 11 21 29 0f 6b "}
vallox/debug {"packetRecv":"01 21 11 00 35 68 "}
vallox/debug {"packetRecv":"01 11 21 35 9f 07 "}
vallox/debug {"packetRecv":"01 21 11 00 a3 d6 "}
vallox/debug {"packetRecv":"01 11 21 a3 01 d7 "}
vallox/debug {"packetRecv":"01 21 11 00 71 a4 "}
**vallox/debug {"packetRecv":"01 11 21 71 c0 64 "}**

As you can see in the last line, the machine is sending me 0x71 back when the switch is activated.

I will try to do some workaround to support your machines fireplace mode better. 
What I'm thinking is something like:
1. Send 'status changed' immediately after switch is pressed
2. Reset the poll timer
3. Query for 0x71H in every poll loop
-> This should query for 0x71H after 15min is passed (5min, 10min, 15min...) so the "fireplace off" event should be quite accurate.

All this is going to be behind a flag for this specific 'DigitSE' ventilation that requires it :-)

Oh, and I could use your help to test it after I've done implementing it, since (obviously) I don't have that machine myself :-)

**Comment by priiduonu** [comment] 2021-05-26 14:06
Looks good to me. May I also suggest that you query the `VX_EXTRA_FUNC_COUNTER`, right now it seems the remaining time is not reported back anywhere?
I am more than happy to test the results, thank you!

**Comment by kotope** [comment] 2021-06-15 05:37
Hi,

Finally I got time to implement and test the flags06 query variable on my machine.

If you have time, please get the latest codes from feature/digit_se_fireplace_query branch (https://github.com/kotope/valloxesp/tree/feature/digit_se_fireplace_query) and enable VALLOX_DIGIT_SE flag from valloxesp.h and try if it works :-)

**Comment by kotope** [comment] 2022-01-18 06:01
Requested feature is in another branch for testing. Closing issue for now.

**Closed** 2022-01-18 06:00 UTC
